export const TEAM_PERMISSIONS = {
    viewer: {
        canViewMembers: true,
        canInvite: false,
        canEditRole: false,
        canRemoveMember: false,
        canManageRoles: false,
        canViewActivity: true,
    },
    editor: {
        canViewMembers: true,
        canInvite: false,
        canEditRole: true,
        canRemoveMember: false,
        canManageRoles: false,
        canViewActivity: true,
    },
    manager: {
        canViewMembers: true,
        canInvite: true,
        canEditRole: true,
        canRemoveMember: true,
        canManageRoles: true,
        canViewActivity: true,
    },
};

export const ROLE_DEFINITIONS = [
    {
        id: 'viewer',
        name: 'Viewer',
        description: 'View-only access to team members and activity',
        permissions: ['canViewMembers', 'canViewActivity'],
    },
    {
        id: 'editor',
        name: 'Editor',
        description: 'Can view members and edit roles',
        permissions: ['canViewMembers', 'canViewActivity', 'canEditRole'],
    },
    {
        id: 'manager',
        name: 'Manager',
        description: 'Full access to team management',
        permissions: ['canViewMembers', 'canInvite', 'canEditRole', 'canRemoveMember', 'canManageRoles', 'canViewActivity'],
    },
];

export const MOCK_TEAM_MEMBERS = [
    {
        id: '1',
        user_id: 'user-001',
        name: 'Sarah Johnson',
        email: 'sarah.johnson@company.com',
        role: 'manager',
        status: 'active',
        department: 'Operations',
        last_active: '2 minutes ago',
        avatar: 'SJ',
    },
    {
        id: '2',
        user_id: 'user-002',
        name: 'Michael Chen',
        email: 'michael.chen@company.com',
        role: 'editor',
        status: 'active',
        department: 'Environmental',
        last_active: '15 minutes ago',
        avatar: 'MC',
    },
    {
        id: '3',
        user_id: 'user-003',
        name: 'Emma Davis',
        email: 'emma.davis@company.com',
        role: 'viewer',
        status: 'active',
        department: 'Compliance',
        last_active: '1 hour ago',
        avatar: 'ED',
    },
    {
        id: '4',
        user_id: 'user-004',
        name: 'James Wilson',
        email: 'james.wilson@company.com',
        role: 'editor',
        status: 'pending',
        department: 'Sustainability',
        last_active: 'Never',
        avatar: 'JW',
    },
    {
        id: '5',
        user_id: 'user-005',
        name: 'Lisa Anderson',
        email: 'lisa.anderson@company.com',
        role: 'viewer',
        status: 'active',
        department: 'Governance',
        last_active: '30 minutes ago',
        avatar: 'LA',
    },
];

export const MOCK_ACTIVITY = [
    {
        id: 'act-001',
        performed_by: 'Sarah Johnson',
        action: 'Added member',
        target_type: 'team_member',
        target_id: 'user-002',
        metadata: { email: 'michael.chen@company.com' },
        timestamp: '2 hours ago',
    },
    {
        id: 'act-002',
        performed_by: 'Michael Chen',
        action: 'Changed role to',
        target_type: 'team_member',
        target_id: 'user-005',
        metadata: { role: 'editor' },
        timestamp: '4 hours ago',
    },
    {
        id: 'act-003',
        performed_by: 'Sarah Johnson',
        action: 'Invited member',
        target_type: 'team_member',
        target_id: 'user-004',
        metadata: { email: 'james.wilson@company.com' },
        timestamp: '1 day ago',
    },
    {
        id: 'act-004',
        performed_by: 'Lisa Anderson',
        action: 'Viewed activity',
        target_type: 'activity_log',
        target_id: null,
        metadata: {},
        timestamp: '2 days ago',
    },
    {
        id: 'act-005',
        performed_by: 'Sarah Johnson',
        action: 'Updated permissions',
        target_type: 'role',
        target_id: 'editor',
        metadata: { changes: 'canEditRole' },
        timestamp: '3 days ago',
    },
];
